# Generated by Django 4.0.3 on 2022-03-24 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('ansible_network_os', models.CharField(blank=True, max_length=16, null=True)),
                ('ansible_connection', models.CharField(blank=True, max_length=16, null=True)),
                ('ansible_user', models.CharField(blank=True, max_length=16, null=True)),
                ('ansible_password', models.CharField(blank=True, max_length=16, null=True)),
                ('ansible_become_pass', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('ipaddr', models.GenericIPAddressField(unique=True)),
                ('groups', models.ForeignKey(default='all', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.group')),
            ],
        ),
    ]
