# Generated by Django 4.0.3 on 2022-03-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_group_groups_remove_group_vars_host_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('var_name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('var_content', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='host',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='groups',
            field=models.ManyToManyField(default='ungrouped', to='inventory.host'),
        ),
        migrations.AddField(
            model_name='group',
            name='vars',
            field=models.ForeignKey(default=dict, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.variable'),
        ),
    ]
