# Generated by Django 4.0.3 on 2022-03-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_group_groups_group_hosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='hosts',
            field=models.ManyToManyField(blank=True, default=['ungrouped'], to='inventory.host'),
        ),
    ]
