# Generated by Django 4.0.3 on 2022-03-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_group_hosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='inventory.host'),
        ),
    ]
