# Generated by Django 4.0.3 on 2022-03-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_publication_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
        migrations.RemoveField(
            model_name='pgroup',
            name='members',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PGroup',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
