# Generated by Django 4.0.3 on 2022-03-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_membership_group_remove_membership_inviter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='hosts',
        ),
        migrations.AddField(
            model_name='host',
            name='groups',
            field=models.ManyToManyField(blank=True, default='all', to='inventory.group'),
        ),
    ]
