# Generated by Django 4.0.3 on 2022-03-24 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_group_hosts_host_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='vars',
            field=models.ForeignKey(blank=True, default=dict, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.variable'),
        ),
    ]
