# Generated by Django 4.0.3 on 2022-03-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_group_vars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='vars',
            field=models.ForeignKey(default=dict, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.variable'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='var_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
