# Generated by Django 4.0.3 on 2022-03-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('template_content', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
